apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongodb-pod
  template:
    metadata:
      labels:
        app: mongodb-pod

    spec:
      containers:
      - name: mongodb
        image: mongo
        envFrom:
          - configMapRef:
              name: mongo-config
          - secretRef:
              name: mongo-secret
        
        ports:
        - containerPort: 27017
        volumeMounts:
          - mountPath: /data/db
            name: backup-volume
      
      volumes:
        - name: backup-volume
          # hostPath:
          #   path: /hosthome/dattatray
          persistentVolumeClaim:
            claimName: pvc1