apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels:
    type: local 
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  #storageClassName: local-storage
  hostPath:
    path: /mongodb/data
  